### ISSUE TITLE
Complete process of making proxies for all NEH files (1)

### ISSUE THREAD

**Issue by DraxIndustries79** [WGBH-MLA/dr-transcode#3]
## Story
NEH proxies should be complete by March 31, 2024.  The project is due in June, but we need time for QA and Avalon ingest, etc.

## Acceptance
- [ ] Complete NEH Proxies by March 31

```[tasklist]
### Tasks
- [ ] Migrate to CLAMS Cluster
- [ ] Estimate average cost per transcode
- [ ] Estimate total number
- [ ] Estimate total cost
```
